### ISSUE TITLE
BigDecimal nil inconsistency with numeric classes

### ISSUE THREAD

**Issue by joseramonc** [ruby/bigdecimal#100]
Hello, I'm trying to migrate my app `Float`s to `BigDecimal`s, but I'm finding it inconsistent with other numeric classes. 

```
nil.to_i # => 0
nil.to_f # => 0.0
nil.to_d # => undefined method `to_d' for nil:NilClass
```

Would you be interested in me sending a PR for this case? I'd be happy to help

**Comment by mrkn** [comment]
@joseramonc If you can write a pull-request for this issue, please send it.
