### ISSUE TITLE
Win 10, Can't Update: MSYS2 Required

### ISSUE THREAD

**Issue by tajmone** [ruby/bigdecimal#129]
After updating Ruby to v2.6:

    ruby 2.6.0p0 (2018-12-25 revision 66547) [x64-mingw32]

Current gem status:

```
>gem outdated
bigdecimal (1.4.1 < 1.4.3)
```

Failure to update digdecimal gem on Win 10 x64 due to MSYS2 not on the system:

```
>gem update bigdecimal
Updating installed gems
Updating bigdecimal
MSYS2 could not be found. Please run 'ridk install'
or download and install MSYS2 manually from https://msys2.github.io/
```

**Comment by tajmone** [comment]
I realized that this is an issue relate to the new Ruby Install changes:

https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-choco-install

Seems that I'll have to install MSYS2 one way or the other. What got me stuck here is that there are 3 options to the `ridk install` command mentioned in the `gem update` error, but couldn't work out which ones to go for.

Anyhow, I thought worth mentioning the problem for other users like me, who update Ruby via the Chocolatey package might suddenly stumble upon this new problem.

**Comment by tajmone** [comment]
Since I brought up the issue I might as well post the solution to the problem...

Assuming you have installed [Ruby via Chocolatey], just install also the [MSYS2 Chocolatey] package. Once it's done, open the CMD:

```
ridk install 2 3
gem update
```

It's as simple as that (except that maybe you didn't want to install MSYS2 in the first place, but with the newer Ruby installer that's the way it so, tuff luck).

[Ruby via Chocolatey]: https://chocolatey.org/packages/ruby

[MSYS2 Chocolatey]: https://chocolatey.org/packages/msys2

**Comment by mrkn** [comment]
@tajmone I'm sorry, I couldn't understand what should I do for this issue because I don't have enough knowledge of Windows environment.  Would you please describe it?

**Comment by mrkn** [comment]
@tajmone Thank you for the explanation.
I'll write about `ridk install 2 3` command in README.  Is it enough for Windows users?

**Comment by kou** [comment]
It's needed only for Windows users who install Ruby by Chokolatey. Windows users who install Ruby by RubyInstaller for Windows directly don't need to anything. Because https://rubyinstaller.org/downloads/ recommends that normal users install Ruby with devkit.

I have no data but I think that direct RubyInstaller users are majority.

I think that putting a link to https://chocolatey.org/packages/msys2 is better because the page describes `ridk install 2 3` and more.

**Comment by tajmone** [comment]
Thanks for the clarification @kou, this point wasn't clear to me although I spent over an hour jumping from the various docs of Ruby Installer and the Chocolatey package. 

This whole situation made me unsure about potential MSYS2 issues and wether installing it manually, via Choco, using `ridk`, etc., could create duplicates or introduce conflicts.

> I have no data but I think that direct RubyInstaller users are majority.

I have no clue either, by the Ruby Chocolatey package mentions over 684,986 download, so it's definitely quite popular too.

> I'll write about ridk install 2 3 command in README. Is it enough for Windows users?

Only if MSYS2 is already on the system one way or another — via Ruby + Dev Kit, installed manually or via Chocolatei, or installed via `ridk install 1` for ridk also installs MSYS2 from scratch:

```
D:\>ridk install
 _____       _           _____           _        _ _         ___
|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

   1 - MSYS2 base installation
   2 - MSYS2 system update (optional)
   3 - MSYS2 and MINGW development toolchain

Which components shall be installed? If unsure press ENTER [1,2,3]
```

I think that if someone has installed Ruby via Chocolatey he/she should also install MSYS2 via Choco (and viceversa) for both are desgined with options that would work well with other too. The Choco packages for Ruby and MSYS integrate well with each other:

- https://chocolatey.org/packages/msys2

> ### Ruby integration
> 
> This package can be used with [ruby](https://chocolatey.org/packages/ruby) package to provide native building environment for gems.
> 
> - The ruby installer comes with `ridk` function which offers interactive GUI installation wizard of msys2 and hence [can't be used unattended](https://github.com/oneclick/rubyinstaller2/issues/79) (`ridk install 1`).
> - Its system update is the same as initialization done with this package (`ridk install 2`).
> - Ruby installer offers unattended setup of MSYS2 and MINGW development toolchain (`ridk install 3`).
> 
> You can also just install the msys2 package without system update and use `ridk` afterwards:
> 
> ```powershell
> cinst ruby                        # install ruby
> cinst msys2 --params "/NoUpdate"  # install msys2 without system update
> Update-SessionEnvironment         # refresh environment vars
> ridk install 2 3                  # use ruby's ridk to update the system and install development toolchain
> ```

**Comment by nobu** [comment]
Does this happen still?

This isn’t a problem of bigdecimal, but rather a problem of RubyInstaller and/or Chocolatey, which affects other extension library gems.  Should be discussed there.

**Comment by tajmone** [comment]
> Does this happen still?

Never happened again after I filed this issue.
