### ISSUE TITLE
LoadError, rails controller generate

### ISSUE THREAD

**Issue by bhagwandassoni1953** [ruby/bigdecimal#136]
![Screenshot_20190429-130002](https://user-images.githubusercontent.com/49839115/56882054-04c6b400-6a80-11e9-8c10-e2fab4177bfa.png)

**Comment by mrkn** [comment]
@bhagwandassoni1953 What the version of ruby do you use?

**Comment by mrkn** [comment]
@bhagwandassoni1953 The new version of bigdecimal, 1.4.4, doesn't have this issue.  Try with the new version again.
