### ISSUE TITLE
Inconsistent conversion/treatment of nil

### ISSUE THREAD

**Issue by kitebuggy** [ruby/bigdecimal#143]
Nil is treated differently for two similar functions:
- BigDecimal(nil) #=> TypeError (can't convert nil into BigDecimal)
- nil.to_d #=> 0.0

This is probably as a result of the PR submitted for this [closed issue #100 ](https://github.com/ruby/bigdecimal/issues/100).

Not sure which of the two would be best, as there are benefits in both approaches, but a consistent approach may be desirable here?

**Comment by mrkn** [comment]
I don't think those two are inconsistent. They just follow the behaviors of`Float(nil)` and `nil.to_f`.

```
irb(main):001:0> Float(nil)
Traceback (most recent call last):
        5: from /Users/mrkn/.rbenv/versions/2.6/bin/irb:23:in `<main>'
        4: from /Users/mrkn/.rbenv/versions/2.6/bin/irb:23:in `load'
        3: from /Users/mrkn/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):1
        1: from (irb):1:in `Float'
TypeError (can't convert nil into Float)
irb(main):002:0> nil.to_f
=> 0.0
```

If you want to discuss such conversion methods of Numeric classes, please go to bugs.ruby-lang.org.
