### ISSUE TITLE
BigDecimal#to_s is returning an `ASCII-8BIT` encoded string

### ISSUE THREAD

**Issue by tahanson** [ruby/bigdecimal#159]
For other `Numeric` types in Ruby, `#to_s` returns an `US-ASCII` encoded string. Not sure if there is a reason for using the `ASCII-8BIT` for BigDecimal but it seems like it should follow the same pattern. 

I noticed this issue in Ruby 2.6.5 when running code similar to:
```
require 'csv'
require 'bigdecimal'

str = ""
str << CSV.generate_line([BigDecimal("-42.00").to_s("F"), "’"])
#  => "-42.0,\xE2\x80\x99\n"
str << CSV.generate_line([nil, "’"])
```
This throws an `Encoding::CompatibilityError (incompatible character encodings: ASCII-8BIT and UTF-8)` error.

Integer works fine because it returns a `US-ASCII` encoded string:
```
str = ""
str << CSV.generate_line([Integer(42).to_s, "’"])
# => "42,’\n"
str << CSV.generate_line([nil, "’"])
# => "42,’\n,’\n"
```
Using a `StringIO` object instead of a standard `String` object is a more sensible way to do this and does solve the issue. Still, seems strange to have the discrepancy in string encoding between `Numeric` types.

**Comment by mrkn** [comment]
It isn't intentional behavior that `BigDecimal#to_s` returns ASCII-8BIT strings.
I'll fix it.

Thank you for your report.

**Comment by eregon** [comment]
As a note, the MRI tracker issue for this is https://bugs.ruby-lang.org/issues/17011
