### ISSUE TITLE
BigDecimal#round behaviour is inconsistent and/or documentation is incorrect

### ISSUE THREAD

**Issue by pnomolos** [ruby/bigdecimal#164]
The docs for `round` specify:

> Round to the nearest integer (by default), returning the result as a BigDecimal.

However, this is inconsistent with what is actually happening:

```ruby
> BigDecimal.new("10.5").round.class
=> Integer

> BigDecimal.new("10.5").round(1).class
=> BigDecimal

> BigDecimal.new("10.5").round(-1).class
=> BigDecimal
```

It would appear the issue lies here: https://github.com/ruby/bigdecimal/blob/master/ext/bigdecimal/bigdecimal.c#L1846

and it seems that `truncate` has the same behaviour (I haven't checked any other methods yet).

Generally this wouldn't matter (I reproduced it because I'm porting a 10+ year-old application) but in some cases it means some methods expected to be available no longer are.  I'm not sure what the actually expected behaviour is, but am willing to help out either updating the docs or the code, depending on which is currently incorrect :)

**Comment by jeremyevans** [comment]
Matz decided that round with no argument or with an argument less than 1 should return integer (https://bugs.ruby-lang.org/issues/12780#note-9).  I've submitted #170 to implement this decision.

**Comment by pnomolos** [comment]
@jeremyevans Thanks for that.

**Comment by casperisfine** [comment]
@jeremyevans there might be another issue though:

```ruby
p BigDecimal('0.1e3').round(0)
```

2.7.2 returns:
```
0.1e3
```

Which is questionable, but not totally wrong.

3.0.0 returns:
```
100
```

Which I just can't make sense of.

**Comment by casperisfine** [comment]
Argh, scratch that, I must be tired, `0.1e3 == 100.0`, so it does make sense.
