### ISSUE TITLE
Why this gem vs Ruby's own BigDecimal class?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [ruby/bigdecimal#167]
Hello!

I just started incorporating BigDecimal into an app and I came across this gem.

My apologies if this is a stupid question (I couldn't find it in the readme), but why use this gem over Ruby's own built-in BigDecimal class? 

https://docs.ruby-lang.org/en/2.7.0/BigDecimal.html

Again, I'm not trying to be rude or anything, just trying to understand the differences/advantages and decide which I should use.

Thank you!

**Comment by jeremyevans** [comment]
This is the same gem as is included in Ruby's standard library.  It's one of the default gems.
