### ISSUE TITLE
undefined method `new' for BigDecimal:Class

### ISSUE THREAD

**Issue by KM8Oz** [ruby/bigdecimal#189]
root@# rubyrep scan -c sync.conf 
Exception caught: undefined method `new' for BigDecimal:Class

**Comment by KM8Oz** [comment]
ok thanks. i will try after and see. its just i'm not familiar with Ruby.

**Comment by olleolleolle** [comment]
@KM8Oz rubyrep was last updated in 2017, and the Ruby version which was current then had a different API for BigDecimal (which is a part of the Ruby standard library). To use rubyrep, you may need an older Ruby version. Example of a release in 2017: https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/
