### ISSUE TITLE
Weird behavior `1_000_000_000.12345.to_d` in bigdecimal 3.0.1

### ISSUE THREAD

**Issue by kamipo** [ruby/bigdecimal#192]
I've found weird behavior in bigdecimal 3.0.1 when I was testing https://github.com/rails/rails/pull/42125.

### Expected behavior

```ruby
1_000_000_000.12345.to_d #=> 0.100000000012345e10
1.000_000_000_12345.to_d #=> 0.100000000012345e1
```

### Actual behavior

```ruby
1_000_000_000.12345.to_d #=> 0.1e10
1.000_000_000_12345.to_d #=> 0.1e1
```

|                          | 2.0.2                | 3.0.0                | 3.0.1                |
|:-------------------------|:--------------------:|:--------------------:|:--------------------:|
| 1_000_000_000.12345.to_d | 0.100000000012345e10 | 0.100000000012345e10 | 0.1e10 (!?)          |
| 1_000_000_0001.2345.to_d | 0.100000000012345e11 | 0.100000000012345e11 | 0.100000000012345e11 |
| 1_000_000_00012.345.to_d | 0.100000000012345e12 | 0.100000000012345e12 | 0.100000000012345e12 |
| 1_000_000_000123.45.to_d | 0.100000000012345e13 | 0.100000000012345e13 | 0.100000000012345e13 |
| 1_000_000_0001234.5.to_d | 0.100000000012345e14 | 0.100000000012345e14 | 0.100000000012345e14 |

**Comment by mrkn** [comment]
Thank you for the report.  I couldn't remember the bugs including this are remaining in the master branch before releasing 3.0.1. 🤦
