### ISSUE TITLE
Conversion issues

### ISSUE THREAD

**Issue by colinbruce** [ruby/bigdecimal#194]
We have noticed another peculiar behaviour in decimal conversions... feel free to close if this should be referenced in an ongoing PR/issue.

Config `ruby 2.7.1p83`

### Expected behavior
`'98.6'.to_d.eql?(0.986e2) => true`

### Actual behaviour

`'98.6'.to_d.eql?(0.986e2) => false`

### Fuller description
Steps to reproduce

```ruby
% irb
2.7.1 :001 > require 'bigdecimal/util'
 => true
2.7.1 :002 > '98.6'.to_d
 => 0.986e2
2.7.1 :003 > '98.6'.to_d.eql?(0.986e2)
 => false
2.7.1 :004 > '98.7'.to_d
 => 0.987e2
2.7.1 :005 > '98.7'.to_d.eql?(0.987e2)
 => true
2.7.1 :006 >
```

This has been spotted during a test suite that generated a random number but it seems to boil down to this issue, sometimes it just cannot match the values 😕 

It seems to happen with numbers between 50 & 99 when the decimal is .6 but I have no idea why!

**Comment by colinbruce** [comment]
Some more detail, this is in a rails app but the step above reduces it to the base level, in fact we have test block like this 

```ruby
context 'a valid parameter is entered' do
  let(:new_value) { rand(1...1_000_000.0).round(2) }

  it 'updates the value - NEW' do
    expect(object.value).to eq(BigDecimal(new_value, new_value.to_s.length -1))
  end

  it 'updates the value - OLD' do
    expect(object.value).to eq(new_value)
  end
end
```

| When new_value equals | New test | Old test |
| --- | --- | --- | 
| 83.6 | passes | fails |
| 83.7 | passes | passes |
| 98.5 | passes | passes |
| 98.6 | passes | fails |
| 98.7 | passes | passes |
| 103.6 | passes | passes |

So we have a fix for now, but would love to know what caused it 👍

**Comment by mrkn** [comment]
In old versions of bigdecimal, this behavior is not a bug but is the specification due to the floating-point error.
This behavior has already been changed in the master branch.

```
$ ruby -Ilib -Iext/bigdecimal -rbigdecimal/util -e 'p BigDecimal::VERSION, 0.986e2.to_d == 0.986e2'
"3.1.0-dev"
true
```
