### ISSUE TITLE
bignum too big to convert into `long' (RangeError)

### ISSUE THREAD

**Issue by casperisfine** [ruby/bigdecimal#199]
On current ruby 3.1:
```
>> BigDecimal::VERSION
=> "3.1.0-dev"
>> BigDecimal(-10000000000000000000)
(irb):2:in `BigDecimal': bignum too big to convert into `long' (RangeError)
```

On 3.0:

```
>> BigDecimal::VERSION
=> "3.0.0"
>> BigDecimal(-10000000000000000000)
=> -0.1e20
```

**Comment by casperisfine** [comment]
Actually, it seems that the trigger is Ruby 3.1 and not the latest bigdecimal version. I'll try to track this down.

**Comment by casperisfine** [comment]
Ok, so the problem is in https://github.com/ruby/bigdecimal/commit/4792a917d806ca1059c952f489413073ea51bf01

When dealing with signed integers, comparing `rb_absint_size` to `sizeof long` is no longer correct.

cc @mrkn

**Comment by mrkn** [comment]
@casperisfine Thank you for reporting and investigating this!

**Comment by casperisfine** [comment]
Thanks for the merge!
