### ISSUE TITLE
BigDecimal#n_significant_digits and #precision do not return the correct value

### ISSUE THREAD

**Issue by alcolmenar** [ruby/bigdecimal#249]
### Issue

In bigdecimal v3.1.3 and ruby 3.0.5,

```ruby
ruby -rbigdecimal -e "p BigDecimal('20.0').n_significant_digits"
1

ruby -rbigdecimal -e "p BigDecimal('20.0').precision"
2
```

### Expectation

The result of significant digits should be 3. Comparing the result of precision to Scala's implementation (Java's implementation behind the scenes), precision should return 3 as well.

**Comment by mrkn** [comment]
BigDecimal handles `20`, `20.0`, `20.00`, and `2e1` as the same.
