### ISSUE TITLE
Please publish 3.1.8-java gem

### ISSUE THREAD

**Issue by andsel** [ruby/bigdecimal#295]
Hi, from [rubygems](https://rubygems.org/gems/bigdecimal) the latest following artifacts are present:
- [3.1.8](https://rubygems.org/gems/bigdecimal/versions/3.1.8) - May 07, 2024 (86.5 KB)
- [3.1.7-java](https://rubygems.org/gems/bigdecimal/versions/3.1.7-java) - March 14, 2024 java (11.5 KB)
- [3.1.7](https://rubygems.org/gems/bigdecimal/versions/3.1.7) - March 14, 2024 (86 KB)
- [3.1.6-java](https://rubygems.org/gems/bigdecimal/versions/3.1.6-java) - January 18, 2024 java (11.5 KB)
- [3.1.6](https://rubygems.org/gems/bigdecimal/versions/3.1.6) - January 18, 2024 (86 KB)

Actually (2024/05/07) the `3.1.8-java` gem is missed.

Please, could you publish that 🙏

**Comment by hsbt** [comment]
Sorry to inconvenient experience. I published https://rubygems.org/gems/bigdecimal/versions/3.1.8-java now.

**Comment by andsel** [comment]
Thanks a lot for the quick turn-around. Now it works perfectly 👍
