### ISSUE TITLE
Is a format `"1.e+00"` invalid in Ruby 2.4.0 or later?

### ISSUE THREAD

**Issue by koic** [ruby/bigdecimal#47]
I hava a question.

The string representation accepted as a BigDecimal has become strict with the following commit.

https://github.com/ruby/bigdecimal/commit/3081a627cebdc1fc119425c7a9f009dbb6bec8e8

```sh
% ruby -v
ruby 2.4.0dev (2016-12-13 trunk 57069) [x86_64-darwin13]
% irb
> require "bigdecimal"
> sprintf("%#.0e", 1) #=> "1.e+00"
> BigDecimal("1.e+00") #=> ArgumentError: invalid value for BigDecimal(): "1.e+00"
```

For example, the `sprintf` document shows a format like `"1.e+00"`.

https://github.com/ruby/ruby/blob/v2_4_0_rc1/sprintf.c#L354

Is this format (`"1.e+00"`) not recommended as a BigDecimal library anymore?

Thanks.

**Comment by mrkn** [comment]
Thank you for reporting.  This is a bug.  I'll fix asap.

**Comment by mrkn** [comment]
I'm sorry.  I've misread `1.e+00` as `1e+00`.
The former is invalid string because `Float()` don't accept it.

```
irb(main):001:0> Float("1.e+00")
ArgumentError: invalid value for Float(): "1.e+00"
        from (irb):1:in `Float'
        from (irb):1
        from /Users/mrkn/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

So this is not a bug, but a new specification.

**Comment by koic** [comment]
Thank you for your reply.

I understood it as a new specification. Thanks.
