### ISSUE TITLE
Can we drop ruby 1_9_3 from CI matrix?

### ISSUE THREAD

**Issue by yui-knk** [ruby/bigdecimal#52]
Tests for Ruby 1.9.3 have been failed.
There are some reasons why tests on 1.9.3 do not work.

* Invalid syntaxes about keyword args (e.g. `**opt` or `method(a: :b)`)
* A missed macoro (`NUM2USHORT `)

I tried to run tests on 1.9.3 (https://github.com/yui-knk/bigdecimal/commits/1_9_3), but I feel it is too complex. So I propose to drop 1.9.3 from CI 😢

**Comment by mrkn** [comment]
It's good idea.
