### ISSUE TITLE
Precision with multiplications and divisions

### ISSUE THREAD

**Issue by arthurchui** [ruby/bigdecimal#6]
I would expect BigDecimal to support arbitrary-precision calculation in a way that it does not lose accuracy after a series of multiplications and divisions. 

``` ruby
2.1.4 :004 > BigDecimal("3000") / BigDecimal("3600") * BigDecimal("3600")
 => #<BigDecimal:7f9dc244d880,'0.2999999999 9999999988E4',27(36)>
2.1.4 :005 > (BigDecimal("3000") / BigDecimal("3600") * BigDecimal("3600")).to_s
 => "0.29999999999999999988E4"
```

^ Should I expect to get back `3000` or is it a bug?

``` ruby
2.1.4 :006 > BigDecimal("3000") * BigDecimal("3600") / BigDecimal("3600")
 => #<BigDecimal:7f9dc241d298,'0.3E4',9(36)>
2.1.4 :007 > _.to_s
 => "0.3E4"
```

^ If it performs multiplication first, it does not involve floating-point calculation and the result is correct as expected.

**Comment by mrkn** [comment]
@arthurchui `3000 / 3600`, namely `5 / 6`, is repeating decimal (0.833....) in the decimal system.
That couldn't be represent exactly in BigDecimal.
Use Rational instead:

```
irb(main):001:0> 3000 / 3600r * 3600
=> (3000/1)
```
