### ISSUE TITLE
[Bug-13331] Inconsistent conversion of Float into Decimal

### ISSUE THREAD

**Issue by mrkn** [ruby/bigdecimal#70]
https://bugs.ruby-lang.org/issues/13331

One would reasonably expect the equality `1.to_d * f == f.t_d` to hold for every Float value `f`, i.e. multiplying by DigDecimal's unit can be viewed as an alternative way of casting Float into Decimal; or simply one could expect that `BigDecimal#*` should always invoke `Float#to_d` on it's argument. Yet for some Floats (e.g. 64.4) the results differ, as showed in the provided script. This can cause a bug in some application contexts.

Originally I asked about that on Stackoverflow:
http://stackoverflow.com/questions/40472933/inconsistent-conversion-of-float-into-decimal-in-ruby/40473007

See the comprehensive answer by Stefan who points out that it is due to different precisions being used in `Float#to_d` and `BigDecimal#*`.

**Comment by casperisfine** [comment]
So I don't have enough context to know wether this was expected or not, but this precision change in `Float#to_d` did cause a lot of issues for us, for instance:


2.7:
```
$ ruby -rbigdecimal/util -e 'p 999_999.9999.to_d'
0.9999999999e6
```


3.0:
```
$ ruby -rbigdecimal/util -e 'p 999_999.9999.to_d'
0.9999999999000001e6
```

So this break a lot of tests for us.

**Comment by mrkn** [comment]
> So this break a lot of tests for us.

What kind of tests?

**Comment by casperisfine** [comment]
Various unit tests in our app, like. tax calculation tests etc. e.g.:

```
--- expected
+++ actual
@@ -1 +1 @@
-{"data"=>{"node"=>{"taxLines"=>[{"title"=>"GST", "price"=>"1.40", "rate"=>0.07, "ratePercentage"=>7.0}, {"title"=>"PST", "price"=>"1.60", "rate"=>0.08, "ratePercentage"=>8.0}]}}}
+{"data"=>{"node"=>{"taxLines"=>[{"title"=>"GST", "price"=>"1.40", "rate"=>0.07, "ratePercentage"=>7.000000000000001}, {"title"=>"PST", "price"=>"1.60", "rate"=>0.08, "ratePercentage"=>8.0}]}}}
```

**Comment by mrkn** [comment]
Could you please use bigdecimal 2.0.2 until this issue will be fixed?

**Comment by casperisfine** [comment]
Well, for now I use a monkey patch to restore the old behavior.

**Comment by mrkn** [comment]
The reason why this change is introduced is there are float numbers that require `Float::DIG + 1` digits to keep the value.  `Math::PI` is one of such the numbers:

```
$ irb
irb(main):001:0' gem 'bigdecimal', '2.0.2'
=> true
irb(main):002:0> require 'bigdecimal/util'
=> true
irb(main):003:0> Math::PI.to_d.to_f == Math::PI
=> false
```

We need to change the rule of the conversion from Float to BigDecimal to fix your problem.
I need more time for consideration and experiments.

**Comment by casperisfine** [comment]
> I need more time for consideration and experiments.

Thank you for considering the issue.

**Comment by mrkn** [comment]
@casperisfine Could you check the latest master branch?

**Comment by casperisfine** [comment]
Looks like the gem doesn't work properly when used as a git repo:

```
extconf.rb:9:in `check_bigdecimal_version': undefined method `[]' for nil:NilClass (NoMethodError)
```

I'll see if I can fix this.

**Comment by ghiculescu** [comment]
https://github.com/ruby/bigdecimal/pull/180 is causing Rails tests to fail against ruby-head (see https://github.com/rails/rails/pull/41115 - [this test](https://github.com/rails/rails/blob/master/activerecord/test/cases/validations/numericality_validation_test.rb#L84..L93) is now failing)

It's debatable if this is a fix or a regression. What do you think @mrkn ?

If you think it's correct now, I can just update the Rails test.

Using ruby-head installed via RVM:

```ruby
 :001 > RUBY_RELEASE_DATE
 => "2021-01-14"
 :002 > require 'bigdecimal'
 => true
 :003 > require 'bigdecimal/util'
 => true
 :004 > 123.455.to_d(5)
 => 0.12346e3
```

Using ruby 3.0 installed via RVM:

```ruby
3.0.0 :001 > RUBY_VERSION
 => "3.0.0"
3.0.0 :002 > require 'bigdecimal'
 => true
3.0.0 :003 > require 'bigdecimal/util'
 => true
3.0.0 :004 > 123.455.to_d(5)
 => 0.12345e3
```

**Comment by mrkn** [comment]
@ghiculescu Good catch.  Probably I need to handle the rounding mode in that case. Could you please make a new issue?

**Comment by mrkn** [comment]
@casperisfine Oops.  I'll take it and check gem installability in CI workflows.

**Comment by mrkn** [comment]
@casperisfine I've already checked gem installability on CI workflows at [this line](https://github.com/ruby/bigdecimal/blob/master/.github/workflows/ci.yml#L55).
Could you please how to reproduce the problem?

**Comment by ghiculescu** [comment]
I actually think the new behavior is correct, since it now matches `Float#round`:

```ruby
3.0.0 :001 > RUBY_VERSION
 => "3.0.0"
3.0.0 :002 > 123.455.round(2)
 => 123.46
```

So `123.455.round(2) == 123.455.to_d(5)` is now true, where it used to be false.

Given that do you still want me to add an issue?

**Comment by mrkn** [comment]
@ghiculescu `to_d` is not the same as just `round`, but as `round` with `half: :even` parameter because `dtoa` uses banker's rounding.

```
irb(main):001:0> 123.445.round(2)
=> 123.45
irb(main):003:0> 123.445.round(2, half: :even)
=> 123.44
irb(main):002:0> 123.445.to_d(5)
=> 0.12344e3
```

A new issue is not necessary because it is not related to rails.
Could you please rewrite rails's tests?
When you rewrite the tests, please specify `half_even` rounding explicitly like below?

```ruby
BigDecimal.save_rounding_mode do
  BigDecimal.mode(BigDecimal::ROUND_MODE, :half_even)
  # write assertions here
end
```

**Comment by ghiculescu** [comment]
Okay, thanks for the explanation. I'm updating the test in Rails here https://github.com/rails/rails/pull/41115

**Comment by ghiculescu** [comment]
@mrkn sorry if I'm confused, but something doesn't seem right.

On ruby-head, `123.455.to_d` always returns 0.12346e3 no matter what rounding mode I use:

```ruby
require 'bigdecimal'
require 'bigdecimal/util'

BigDecimal.save_rounding_mode do
  BigDecimal.mode(BigDecimal::ROUND_MODE, :down)

  p 123.455.to_d(5) # 0.12346e3
end

BigDecimal.save_rounding_mode do
  BigDecimal.mode(BigDecimal::ROUND_MODE, :up)
  
  p 123.455.to_d(5) # 0.12346e3
end

BigDecimal.save_rounding_mode do
  BigDecimal.mode(BigDecimal::ROUND_MODE, :half_even)
  
  p 123.455.to_d(5) # 0.12346e3
end

BigDecimal.save_rounding_mode do
  BigDecimal.mode(BigDecimal::ROUND_MODE, :half_up)
  
  p 123.455.to_d(5) # 0.12346e3
end
```

This is a change from ruby 3, where `:down`, `:half_even`, and `:half_up` return 0.12345e3, and only `:up` returns 0.12346e3:

```ruby
require 'bigdecimal'
require 'bigdecimal/util'

BigDecimal.save_rounding_mode do
  BigDecimal.mode(BigDecimal::ROUND_MODE, :down)

  p 123.455.to_d(5) # 0.12345e3
end

BigDecimal.save_rounding_mode do
  BigDecimal.mode(BigDecimal::ROUND_MODE, :up)
  
  p 123.455.to_d(5) # 0.12346e3
end

BigDecimal.save_rounding_mode do
  BigDecimal.mode(BigDecimal::ROUND_MODE, :half_even)
  
  p 123.455.to_d(5) # 0.12345e3
end

BigDecimal.save_rounding_mode do
  BigDecimal.mode(BigDecimal::ROUND_MODE, :half_up)
  
  p 123.455.to_d(5) # 0.12345e3
end
```

Which behavior is correct?

**Comment by mrkn** [comment]
@ghiculescu Currently `to_d` always performs half-even rounding.  I think it is a bug of `to_d` (and also of `Kernel.BigDecimal`).  Please use only `half_even` rounding in rails's test.

**Comment by mrkn** [comment]
@ghiculescu Should Rails's test check the behaviors that vary depending on BigDecimal's rounding mode?

**Comment by ghiculescu** [comment]
Okay, so the behavior of `:half_even` has changed - this means the Rails test will need to have different assertions based on the ruby version, correct?

**Comment by mrkn** [comment]
@ghiculescu Yes if Rails' test uses the default version of bigdecimal for each version of Ruby.

**Comment by ghiculescu** [comment]
@mrkn thanks for all your help! I will do that.

Last question: do we need to update https://github.com/ruby/ruby/blob/master/ext/bigdecimal/bigdecimal.gemspec#L3 to match https://github.com/ruby/bigdecimal/blob/master/bigdecimal.gemspec#L3 ?

Currently, if I pull ruby-head, `BigDecimal::VERSION` is 3.0.0 (while `RUBY_VERSION` is 3.1.0). So I have no way of checking based on `BigDecimal::VERSION` yet.

**Comment by casperisfine** [comment]
> Could you please how to reproduce the problem?

@mrkn this way:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'bigdecimal', github: 'ruby/bigdecimal'
end
```

```
$ ruby /tmp/bigdecimal.rb 
Traceback (most recent call last):
	16: from /tmp/bigdecimal.rb:3:in `<main>'
	15: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/inline.rb:54:in `gemfile'
	14: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/settings.rb:115:in `temporary'
	13: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/inline.rb:61:in `block in gemfile'
	12: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/settings.rb:115:in `temporary'
	11: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/inline.rb:62:in `block (2 levels) in gemfile'
	10: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/installer.rb:24:in `install'
	 9: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/installer.rb:72:in `run'
	 8: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/process_lock.rb:9:in `lock'
	 7: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/process_lock.rb:9:in `open'
	 6: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/process_lock.rb:12:in `block in lock'
	 5: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/installer.rb:91:in `block in run'
	 4: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/installer.rb:209:in `install'
	 3: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/installer.rb:285:in `install_in_parallel'
	 2: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/installer/parallel_installer.rb:78:in `call'
	 1: from /Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/installer/parallel_installer.rb:102:in `call'
/Users/byroot/.gem/ruby/2.7.2/gems/bundler-2.2.4/lib/bundler/installer/parallel_installer.rb:197:in `handle_error': Gem::Ext::BuildError: ERROR: Failed to build gem native extension. (Bundler::InstallError)

    current directory: /Users/byroot/.gem/ruby/2.7.2/bundler/gems/bigdecimal-b1f1ed26c93b/ext/bigdecimal
/opt/rubies/2.7.2/bin/ruby -I /opt/rubies/2.7.2/lib/ruby/2.7.0 -r ./siteconf20210114-41444-kuov9j.rb extconf.rb
checking RUBY_BIGDECIMAL_VERSION... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/rubies/2.7.2/bin/$(RUBY_BASE_NAME)
extconf.rb:9:in `check_bigdecimal_version': undefined method `[]' for nil:NilClass (NoMethodError)
	from extconf.rb:43:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/byroot/.gem/ruby/2.7.2/bundler/gems/bigdecimal-b1f1ed26c93b for inspection.
Results logged to /Users/byroot/.gem/ruby/2.7.2/bundler/gems/extensions/x86_64-darwin-19/2.7.0-static/bigdecimal-b1f1ed26c93b/gem_make.out

An error occurred while installing bigdecimal (3.0.1.dev), and Bundler cannot continue.

In Gemfile:
  bigdecimal
```
