### ISSUE TITLE
Removing BigDecimal.new to match core numeric classes like Integer

### ISSUE THREAD

**Issue by mrkn** [ruby/bigdecimal#89]
BigDecimal is going to be immutable and frozen [#84] to match core numeric classes like Integer.
So BigDecimal.new should be removed for the purpose.

**Comment by sodabrew** [comment]
Please advise on what replacement code you suggest in the deprecation notice.

**Comment by mrkn** [comment]
@sodabrew see 26d84ba766e971da8eaaf2ce41e7b89935fa68da
